CREATE TABLE users(
    id BIGINT NOT NULL AUTO_INCREMENT,
    serial VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    CONSTRAINT UNIQUE (username),
    CONSTRAINT UNIQUE (serial),
    CONSTRAINT PRIMARY KEY (id)
);

CREATE TABLE attachments(
    id BIGINT NOT NULL AUTO_INCREMENT,
    serial VARCHAR(255) NOT NULL,
    path TEXT,
    name VARCHAR(255) NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 0,
    user_id BIGINT NOT NULL,
    CONSTRAINT FOREIGN KEY (id) REFERENCES users(id),
    CONSTRAINT UNIQUE (serial),
    CONSTRAINT PRIMARY KEY (id)
);